export TODAY="2025-11-19"

docker exec redis redis-cli SET attack:1 "{\"id\":1,\"timestamp\":\"${TODAY}T09:15:23\",\"targetIp\":\"192.168.1.100\",\"attackType\":\"SQL Injection\",\"payload\":\"' OR 1=1--\"}"
docker exec redis redis-cli SET attack:2 "{\"id\":2,\"timestamp\":\"${TODAY}T09:28:47\",\"targetIp\":\"203.0.113.50\",\"attackType\":\"XSS\",\"payload\":\"<script>alert('HACKED!');</script>\"}"
docker exec redis redis-cli SET attack:3 "{\"id\":3,\"timestamp\":\"${TODAY}T10:05:12\",\"targetIp\":\"185.58.103.9\",\"attackType\":\"Brute Force\",\"payload\":\"admin:password123\"}"
docker exec redis redis-cli SET attack:4 "{\"id\":4,\"timestamp\":\"${TODAY}T10:22:36\",\"targetIp\":\"198.51.100.10\",\"attackType\":\"DDoS\",\"payload\":\"TCP SYN flood attack\"}"
docker exec redis redis-cli SET attack:5 "{\"id\":5,\"timestamp\":\"${TODAY}T11:03:18\",\"targetIp\":\"10.0.0.50\",\"attackType\":\"SQL Injection\",\"payload\":\"UNION SELECT username,password FROM users--\"}"
docker exec redis redis-cli SET attack:6 "{\"id\":6,\"timestamp\":\"${TODAY}T11:41:29\",\"targetIp\":\"172.16.0.1\",\"attackType\":\"Buffer Overflow\",\"payload\":\"AAAAAAAAAAAAAAAA\"}"
docker exec redis redis-cli SET attack:7 "{\"id\":7,\"timestamp\":\"${TODAY}T12:17:44\",\"targetIp\":\"203.0.113.77\",\"attackType\":\"Brute Force\",\"payload\":\"root:admin1234\"}"
docker exec redis redis-cli SET attack:8 "{\"id\":8,\"timestamp\":\"${TODAY}T12:55:08\",\"targetIp\":\"192.168.1.200\",\"attackType\":\"XSS\",\"payload\":\"<img src=x onerror=alert('XSS')>\"}"
docker exec redis redis-cli SET attack:9 "{\"id\":9,\"timestamp\":\"${TODAY}T13:12:33\",\"targetIp\":\"198.51.100.10\",\"attackType\":\"DDoS\",\"payload\":\"UDP amplification attack\"}"
docker exec redis redis-cli SET attack:10 "{\"id\":10,\"timestamp\":\"${TODAY}T13:48:51\",\"targetIp\":\"185.58.103.9\",\"attackType\":\"Unknown Attack\",\"payload\":\"Suspicious binary data\"}"
docker exec redis redis-cli SET attack:11 "{\"id\":11,\"timestamp\":\"${TODAY}T14:06:27\",\"targetIp\":\"10.0.0.75\",\"attackType\":\"SQL Injection\",\"payload\":\"DROP TABLE sessions; --\"}"
docker exec redis redis-cli SET attack:12 "{\"id\":12,\"timestamp\":\"${TODAY}T14:34:15\",\"targetIp\":\"172.16.0.1\",\"attackType\":\"XSS\",\"payload\":\"javascript:void(document.cookie='stolen=true')\"}"
docker exec redis redis-cli SET attack:13 "{\"id\":13,\"timestamp\":\"${TODAY}T15:19:42\",\"targetIp\":\"203.0.113.50\",\"attackType\":\"Brute Force\",\"payload\":\"user:qwerty\"}"
docker exec redis redis-cli SET attack:14 "{\"id\":14,\"timestamp\":\"${TODAY}T15:57:06\",\"targetIp\":\"198.51.100.10\",\"attackType\":\"DDoS\",\"payload\":\"HTTP GET flood\"}"
docker exec redis redis-cli SET attack:15 "{\"id\":15,\"timestamp\":\"${TODAY}T16:23:38\",\"targetIp\":\"192.168.1.100\",\"attackType\":\"SQL Injection\",\"payload\":\"SELECT * FROM admin_users\"}"
docker exec redis redis-cli SET attack:16 "{\"id\":16,\"timestamp\":\"${TODAY}T16:45:19\",\"targetIp\":\"198.51.100.10\",\"attackType\":\"DDoS\",\"payload\":\"High volume traffic flood\"}"
docker exec redis redis-cli SET attack:17 "{\"id\":17,\"timestamp\":\"${TODAY}T17:11:53\",\"targetIp\":\"185.58.103.9\",\"attackType\":\"Brute Force\",\"payload\":\"admin:letmein\"}"
docker exec redis redis-cli SET attack:18 "{\"id\":18,\"timestamp\":\"${TODAY}T17:39:24\",\"targetIp\":\"192.168.1.100\",\"attackType\":\"XSS\",\"payload\":\"<script>document.location='http://evil.com'</script>\"}"